#!/bin/sh

for test_file in $(find ./ | grep "_test.cpp"); do
  source_file=$(echo "$test_file" | sed -e 's/_test//g')

  echo "[test] $test_file"
  g++ -std=c++20 "$source_file" "$test_file" -L/usr/local/lib -lgtest -lgtest_main
  ./a.out
done

exit 0
