name: Unit test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # 仮

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Install deps
        run: |
          apt-get update
          apt-get install -y g++ cmake

          ./googletest /usr/local/src/googletest
          cd /usr/local/src/googletest
          mkdir build
          cd build
          cmake ..
          make
          make install

      - name: test
        run: ./fulltest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
