name: Unit test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # 仮

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          submodules: true

      - name: test
        run: make fulltest'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
